Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -43,6 +43,13 @@ jobs:
       url: ${{ steps.deployment.outputs.page_url }}
 
     steps:
+      - name: Check if artifact exists
+        run: |
+          if [ ! -d "dist" ]; then
+            echo "Error: 'dist' directory not found. Exiting..."
+            exit 1
+          fi
+
       - name: Download artifact
         uses: actions/download-artifact@v2
         with:
